config/routes.rb
Rails.application.routes.draw do

  get 'users', to: "users#index"
	# get 'signup', to: 'registrations#new', as: 'signup'
	# get 'login', to: 'sessions#new', as: 'login'
	# get 'logout', to: 'sessions#destroy', as: 'logout'

	# devise_scope :users do
	# 	get 'signup', to: 'devise/registrations#new', as: 'signup'
	# 	get 'login', to: 'devise/sessions#new', as: 'login'
	# 	get 'logout', to: 'devise/sessions#destroy', as: 'logout'
	# end

  	devise_for :users, path_names: {sign_in: "login", sign_up: "signup"}, :controllers => {:registrations => "users/registrations"}

  	get 'welcome/index'

  	resources :articles do
  		resources :comments
  	end

  	root 'welcome#index'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  # validates_associated :articles
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# http_basic_authenticate_with name: "Ali rido", password: "ali123", only: :destroy


	def create
		# binding.pry

		@article = Article.find(params[:article_id])
		comment = @article.comments.create(comment_params.merge(user_id: current_user.id))
		if comment.errors.any?
			# flash[:alert] = "Comment cannot post!"
			flash[:alert] = comment.errors.full_messages.join(", ")
		else 
			flash[:notice] = "Commented!"
		end
		redirect_to article_url(@article)
		# @comment = Comment.new(comment_params)
	end

	def destroy
		# @article = Article.find(params[:article_id])
		comment = Comment.find_by(article_id: params[:article_id], user_id: params[:user_id], id: params[:id])
		comment.destroy
		flash[:notice] = "Successfully deleted the comment!"
		redirect_to article_url(params[:article_id])
	end

	private
		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @article.comments.each do |comment| %>

	<p>
	  <strong>User:</strong>
	  <%= comment.user.username %>
	</p>
	 
	<p>
	  <strong>Comment:</strong>
	  <%= comment.body %>
	</p>
	<%= time_ago_in_words(comment.created_at) %>

	<%= link_to 'Delete comment', article_comment_path(comment.article, comment), method: :delete, data: {confirm: 'Are you sure, bro?'} %>

<% end %>
<!-- [comment.article, comment] -->

app/views/comments/_form.html.erb
<%#= form_with (model: [ @article, @article.comments.build ], local: true) do |form| %>

<%= form_with(model: [@article, Comment.new], local: true) do |form| %>
	<!-- pesan error dibawah ini masih ngga bisa. Nanti kembali kesini dan perbaiki! -->
	<%# binding.pry %>
	<%# if @comment && @comment.errors.any? %>
		<!-- <div id="error_explanation">
			<h2> -->
				<%#= pluralize(@comment.errors.count, "error") %><!--  prohibited this comment frorm being saved:
			</h2>
			<ul> -->
				 <%# @comment.errors.full_messages.each do |msg| %>
					<!-- <li><%#= msg %></li> -->
				<%# end %>
			<!-- </ul>
		</div> -->
	<%# end %>
<%#= form_for [@article, Comment.new] do |form| %>
	<p>
		<%= form.label :body %><br>
		<%= form.text_area :body %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>